import type { InsertExercise } from "@shared/schema";

/**
 * PHASE 2 - BUILD BLOCK - 6-Day Push/Pull/Legs\n *\n * Phase 2 reuses Phase 1 warm-up and cool-down blocks; they are merged in ./index.ts.
 *
 * Verbatim program content. Every row is keyed by (program, day, order, number);
 * `syncProgram` in ./index.ts upserts on that key so editing a row here updates
 * the DB in place and keeps existing set_logs pointing at the same exercise id.
 */
export const phase2Exercises: Omit<InsertExercise, "program">[] = [

  // DAY 1 — PUSH A — Machine Shoulder Press + Side Delts + Triceps + Upper Chest
  { day: 1, order: 1, number: "1", name: "Machine Shoulder Press", defaultSets: 4, repRange: "6-10", tempo: "2-1-1-1", rir: "1-2", restSeconds: "120s", notes: "Compound first while fresh. Front + side delt.", alternate: "", videoUrl: "https://youtube.com/shorts/7oH0algsdww", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 2, number: "2", name: "Incline Press (DB or Machine)", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-0", rir: "1-2", restSeconds: "90s", notes: "Upper chest, hit 1 of 2. Chest is weighted to Push B by design.", alternate: "Machine Press", videoUrl: "https://youtube.com/shorts/ou6s32mJgjU", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 3, number: "3", name: "Cable Lateral Raise (single-arm, cable behind body)", defaultSets: 4, repRange: "10-15", tempo: "2-0-1-1", rir: "0-1", restSeconds: "60-75s", notes: "PRIMARY side-delt driver. Lengthened, constant tension. Progress on the stack. Last set: lengthened partials to failure. Straight, full focus.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 4, number: "4a", name: "Lean-In DB Lateral Raise", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "0-1", restSeconds: "60s", notes: "Second side-delt angle, loaded stretch. Superset w/ 4b.", alternate: "", videoUrl: "https://youtube.com/shorts/HeovYNoZDRg", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "P2D1-4", segment: "working" },
  { day: 1, order: 5, number: "4b", name: "Triceps Rope Pushdown", defaultSets: 3, repRange: "10-15", tempo: "2-0-1-1", rir: "0-1", restSeconds: "60s", notes: "Non-competing. Superset w/ 4a.", alternate: "", videoUrl: "https://youtube.com/shorts/u36jNfqh8_U", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D1-4", segment: "working" },
  { day: 1, order: 6, number: "5a", name: "Overhead Cable Triceps Extension (rope)", defaultSets: 4, repRange: "8-12", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75-90s", notes: "Long head in the stretch. Triceps to ¾ on this day. Superset w/ 5b.", alternate: "", videoUrl: "https://youtube.com/shorts/9Ark9S11uXw", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D1-5", segment: "working" },
  { day: 1, order: 7, number: "5b", name: "Reverse Pec Deck", defaultSets: 3, repRange: "15-20", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Rear delt, angle 1 of 3. Superset w/ 5a.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D1-5", segment: "working" },
  { day: 1, order: 8, number: "6a", name: "Cable Crunch", defaultSets: 3, repRange: "12-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Loaded abs, progress it. Superset w/ 6b.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D1-6", segment: "working" },
  { day: 1, order: 9, number: "6b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Daily. Superset w/ 6a.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "P2D1-6", segment: "working" },

  // DAY 2 — PULL A — Lat Width + Biceps + Rear Delts + Side Delts
  { day: 2, order: 1, number: "1", name: "Neutral-Grip Strict Pull-Up", defaultSets: 3, repRange: "6-10", tempo: "2-1-1-1", rir: "1-2", restSeconds: "120s", notes: "Width anchor, fresh. Add load past 10.", alternate: "", videoUrl: "https://youtube.com/shorts/E9vvwfxSZFc", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 2, number: "2", name: "Wide-Grip Lat Pulldown", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "Second vertical, different grip. Full overhead stretch.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 3, number: "3", name: "Chest-Supported Row (lat-biased)", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "Thickness, balances the day's vertical work. Back thickness is now 2×.", alternate: "Machine Row", videoUrl: "https://youtube.com/shorts/eVm92NO-EYI", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 4, number: "4a", name: "Straight-Arm Pulldown", defaultSets: 3, repRange: "12-20", tempo: "2-1-1-1", rir: "1-2", restSeconds: "60s", notes: "Lat iso, lengthened. Superset w/ 4b.", alternate: "", videoUrl: "https://youtube.com/shorts/hAMcfubonDc", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D2-4", segment: "working" },
  { day: 2, order: 5, number: "4b", name: "Incline DB Curl", defaultSets: 3, repRange: "8-12", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Biceps in the stretch. Superset w/ 4a.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "P2D2-4", segment: "working" },
  { day: 2, order: 6, number: "5a", name: "Cable Curl", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "0-1", restSeconds: "60s", notes: "Last set to failure. Superset w/ 5b.", alternate: "", videoUrl: "https://youtube.com/shorts/6n3uYGhIoZI", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D2-5", segment: "working" },
  { day: 2, order: 7, number: "5b", name: "Cable Face Pull", defaultSets: 3, repRange: "15-25", tempo: "2-1-2-1", rir: "1-2", restSeconds: "60s", notes: "Rear delt, angle 2 of 3. Superset w/ 5a.", alternate: "", videoUrl: "https://youtube.com/shorts/8686PLZB_1Q", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D2-5", segment: "working" },
  { day: 2, order: 8, number: "6a", name: "Cable Lateral Raise (finisher)", defaultSets: 3, repRange: "15-25", tempo: "1-0-1-1", rir: "0", restSeconds: "60s", notes: "Side-delt hit 3. Strip the stack on the last set. Superset w/ 6b.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "P2D2-6", segment: "working" },
  { day: 2, order: 9, number: "6b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Superset w/ 6a.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "P2D2-6", segment: "working" },

  // DAY 3 — LEGS A — Warm-Up (mirrors Day 6 leg warm-up)
  { day: 3, order: -12, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow + quad activation.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -11, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Shoulder maintenance even on leg day.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -10, number: "W3", name: "World's Greatest Stretch", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Hip flexors, thoracic, hamstrings — all in one.", alternate: "", videoUrl: "https://youtu.be/-CiWQ2IvY34", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -9, number: "W4", name: "Cossack Squat", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Adductor + hip mobility.", alternate: "", videoUrl: "https://youtube.com/shorts/JfauHQjKVrU", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -8, number: "W5", name: "Pigeon Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip external rotation + glute stretch.", alternate: "", videoUrl: "https://youtube.com/shorts/KUclDkITsS8", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -7, number: "W6", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Prep for calf raises.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -4, number: "R1", name: "Seated Leg Curl — RAMP SET", defaultSets: 1, repRange: "8 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light. Groove the pattern.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -3, number: "R2", name: "Seated Leg Curl — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate. Prep the joints.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },

  // DAY 3 — LEGS A — Ham + Quad + Calves + Side Delts + LISS + Posing
  { day: 3, order: 10, number: "P", name: "Men's Physique Posing Practice", defaultSets: 1, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "Front, Side L, Back, Side R. 60s holds, 3-4 cycles. No LISS Saturday.", alternate: "", videoUrl: "https://youtu.be/knbFPNtI_Gc", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "finisher" },
  { day: 3, order: 1, number: "1", name: "Seated Leg Curl", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "0-1", restSeconds: "75s", notes: "Ham, bent-hip angle. Priority knee-flexion to open the day.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 2, number: "2", name: "Leg Press", defaultSets: 3, repRange: "10-15", tempo: "2-1-1-0", rir: "1-2", restSeconds: "120s", notes: "Second quad compound, deep ROM.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 3, number: "3", name: "Hack Squat", defaultSets: 4, repRange: "8-12", tempo: "3-1-1-0", rir: "1-2", restSeconds: "120-150s", notes: "Loads quad compound, deep loaded stretch. Machine-exclusive, not Saturday.", alternate: "Belt Squat", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 4, number: "4a", name: "Lying Leg Curl", defaultSets: 4, repRange: "8-12", tempo: "2-0-2-1", rir: "1-2", restSeconds: "90s", notes: "Knee-flexion, machine-exclusive to crunch. Superset w/ 4b.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D3-4", segment: "working" },
  { day: 3, order: 5, number: "4b", name: "Leg Extension", defaultSets: 3, repRange: "12-20", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75s", notes: "Antagonist pairing, quad isolation. Superset w/ 4a.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D3-4", segment: "working" },
  { day: 3, order: 6, number: "5a", name: "Seated Calf Raise", defaultSets: 4, repRange: "10-15", tempo: "2-1-2-1", rir: "0-1", restSeconds: "60s", notes: "Soleus, 1s loaded stretch. Superset w/ 5b.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D3-5", segment: "working" },
  { day: 3, order: 7, number: "5b", name: "Machine Lateral Raise", defaultSets: 3, repRange: "12-20", tempo: "2-0-1-1", rir: "0-1", restSeconds: "60s", notes: "Side-delt volume on a non-competing day. Machine-exclusive to crunch. Zero cost to your legs. Superset w/ 5a.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D3-5", segment: "working" },
  { day: 3, order: 8, number: "6a", name: "Hanging Leg Raise", defaultSets: 3, repRange: "10-15", tempo: "—", rir: "1-2", restSeconds: "60s", notes: "Lower abs. Superset w/ 6b.", alternate: "", videoUrl: "https://youtube.com/shorts/KCt2qWYPrMc", inputType: "bodyweight_reps", isSupersetPart: true, supersetGroup: "P2D3-6", segment: "working" },
  { day: 3, order: 9, number: "6b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Superset w/ 6a.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "P2D3-6", segment: "working" },
  { day: 3, order: 11, number: "L", name: "LISS Cardio", defaultSets: 0, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "After workout. HR 110-130. Adjust by feel (Sat=10-15 min).", alternate: "", videoUrl: "https://youtube.com/shorts/JGzA6FPzZS8", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "working" },

  // DAY 4 — PUSH B — Upper Chest + Side Delts #2 + Triceps #2
  { day: 4, order: 1, number: "1", name: "Incline Barbell OR Smith Press", defaultSets: 4, repRange: "6-10", tempo: "2-1-1-0", rir: "1-2", restSeconds: "120s", notes: "Upper-chest anchor, fresh. Last set ~1 RIR.", alternate: "Smith Press", videoUrl: "", inputType: "weight_reps_barbell", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 2, number: "2a", name: "Low-Incline Machine Press", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-0", rir: "1-2", restSeconds: "90s", notes: "Second chest press, overall fullness. Superset w/ 2b.", alternate: "Low-Incline DB Press", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D4-2", segment: "working" },
  { day: 4, order: 3, number: "2b", name: "Machine Decline Press", defaultSets: 4, repRange: "8-13", tempo: "2-1-1-1", rir: "1-3", restSeconds: "90s", notes: "Superset w/ 2a.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D4-2", segment: "working" },
  { day: 4, order: 4, number: "3", name: "Incline Cable / DB Fly", defaultSets: 3, repRange: "12-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Stretch fly, deep bottom. Do not chase load.", alternate: "Incline DB Fly", videoUrl: "https://youtube.com/shorts/VSwFnBqe7gE", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 5, number: "4a", name: "Cable Lateral Raise", defaultSets: 4, repRange: "12-20", tempo: "2-0-1-1", rir: "0-1", restSeconds: "60s", notes: "Side-delt hit 2, higher reps. Superset w/ 4b.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "P2D4-4", segment: "working" },
  { day: 4, order: 6, number: "4b", name: "Overhead Cable Triceps Extension", defaultSets: 3, repRange: "8-12", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Non-competing. Superset w/ 4a.", alternate: "", videoUrl: "https://youtube.com/shorts/9Ark9S11uXw", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D4-4", segment: "working" },
  { day: 4, order: 7, number: "5a", name: "Triceps Pushdown", defaultSets: 4, repRange: "10-15", tempo: "2-0-1-1", rir: "0-1", restSeconds: "60s", notes: "Triceps to ¾ on this day. Last set to failure. Superset w/ 5b.", alternate: "Dip Machine", videoUrl: "https://youtube.com/shorts/u36jNfqh8_U", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D4-5", segment: "working" },
  { day: 4, order: 8, number: "5b", name: "Cable Crunch", defaultSets: 3, repRange: "12-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Loaded abs. Superset w/ 5a.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P2D4-5", segment: "working" },
  { day: 4, order: 9, number: "6", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },

  // DAY 5 — PULL B — Back Thickness + Lat Width #2 + Biceps #2 + Rear Delts #2 + Arms
  { day: 5, order: 1, number: "1", name: "Chest-Supported DB Row (elbow ~30deg)", defaultSets: 4, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90-120s", notes: "Thickness anchor, fresh. Stable torso, no body english.", alternate: "Machine Row", videoUrl: "https://youtube.com/shorts/eVm92NO-EYI", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 2, number: "2", name: "Seated Cable Row (neutral)", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "Mid-back. Reach forward each rep for the stretch.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 3, number: "3", name: "1-Arm Cable Lat Pulldown", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "75s", notes: "Lat width, vertical 1. Unilateral deep stretch.", alternate: "Wide Pulldown", videoUrl: "https://youtube.com/shorts/wYy32uk4Bu8", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 4, number: "4", name: "Pull Down Cycle (Wide, Normal, Reverse Grip)", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "Three-grip sequence each set, no rest between grips.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 5, number: "5a", name: "Spider Curl", defaultSets: 3, repRange: "10-12", tempo: "2-0-2-1", rir: "0-1", restSeconds: "60s", notes: "Biceps shortened-position contrast to Pull A. Superset w/ 5b.", alternate: "Preacher Curl", videoUrl: "https://youtube.com/shorts/HT2Z1MbRXVE", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "P2D5-5", segment: "working" },
  { day: 5, order: 6, number: "5b", name: "Cross-Body Cable Rear Delt", defaultSets: 3, repRange: "15-20", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Rear delt, angle 3 of 3. Superset w/ 5a.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "P2D5-5", segment: "working" },
  { day: 5, order: 7, number: "6a", name: "Hammer Curl", defaultSets: 3, repRange: "10", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Brachialis / forearm. Superset w/ 6b.", alternate: "", videoUrl: "https://youtube.com/shorts/ZFV_yAlxLMU", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "P2D5-6", segment: "working" },
  { day: 5, order: 8, number: "6b", name: "Chest-Supported DB Shrug", defaultSets: 2, repRange: "10-15", tempo: "2-1-2-1", rir: "1-2", restSeconds: "75s", notes: "Moderate only. Big traps shorten the shoulder line and fight the taper. Superset w/ 6a.", alternate: "", videoUrl: "https://youtube.com/shorts/QszCnEqqklU", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "P2D5-6", segment: "working" },
  { day: 5, order: 9, number: "7a", name: "Ab Wheel Rollout", defaultSets: 3, repRange: "10-15", tempo: "3-1-2-0", rir: "1-2", restSeconds: "60s", notes: "Anti-extension. Kneeling. Superset w/ 7b.", alternate: "", videoUrl: "", inputType: "bodyweight_reps_weighted", isSupersetPart: true, supersetGroup: "P2D5-7", segment: "working" },
  { day: 5, order: 10, number: "7b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Superset w/ 7a.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "P2D5-7", segment: "working" },

  // DAY 6 — LEGS B — Quad-First + Ham + Calves + Side Delts + LISS + Posing
  { day: 6, order: 10, number: "P", name: "Men's Physique Posing Practice", defaultSets: 1, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "Front, Side L, Back, Side R. 60s holds. No LISS Saturday.", alternate: "", videoUrl: "https://youtu.be/knbFPNtI_Gc", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "finisher" },
  { day: 6, order: 1, number: "1", name: "Belt Squat", defaultSets: 4, repRange: "6-10", tempo: "3-1-1-0", rir: "1-2", restSeconds: "120-150s", notes: "Quad anchor, heaviest bilateral, fresh. Only bilateral squat the HS has. No back-loaded squat.", alternate: "", videoUrl: "", inputType: "weight_reps_barbell", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 2, number: "2", name: "RDL", defaultSets: 4, repRange: "8-12", tempo: "3-1-1-0", rir: "1-2", restSeconds: "90s", notes: "Hinge goes early, before grip and low back fatigue. Ham via hip extension.", alternate: "DB RDL", videoUrl: "", inputType: "weight_reps_barbell", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 3, number: "3", name: "DB Bulgarian Split Squat", defaultSets: 3, repRange: "8-12/leg", tempo: "2-1-1-0", rir: "1-2", restSeconds: "90s", notes: "One unilateral, not two stacked. Quad/glute under stretch.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 4, number: "4", name: "Nordic Curl", defaultSets: 3, repRange: "6-10", tempo: "3-0-1-0", rir: "1-2", restSeconds: "75s", notes: "Thermal knee-flexion; substitute for the leg curl machine. Banded → slow partials to start. Very high eccentric stress.", alternate: "Banded Nordic", videoUrl: "", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 5, number: "5a", name: "Single-Leg DB Calf Raise", defaultSets: 4, repRange: "10-15", tempo: "2-1-2-1", rir: "0-1", restSeconds: "60s", notes: "Loaded stretch at the bottom. Superset w/ 5b.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "P2D6-5", segment: "working" },
  { day: 6, order: 6, number: "5b", name: "Lean-In DB Lateral Raise", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "0-1", restSeconds: "60s", notes: "Side-delt volume, DB version since the HS has no lateral machine. Zero cost to your legs. Superset w/ 5a.", alternate: "", videoUrl: "https://youtube.com/shorts/HeovYNoZDRg", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "P2D6-5", segment: "working" },
  { day: 6, order: 7, number: "6a", name: "Hanging Leg Raise", defaultSets: 3, repRange: "10-15", tempo: "—", rir: "1-2", restSeconds: "60s", notes: "Lower abs. Superset w/ 6b.", alternate: "", videoUrl: "https://youtube.com/shorts/KCt2qWYPrMc", inputType: "bodyweight_reps", isSupersetPart: true, supersetGroup: "P2D6-6", segment: "working" },
  { day: 6, order: 8, number: "6b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Superset w/ 6a.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "P2D6-6", segment: "working" },
  { day: 6, order: 11, number: "L", name: "LISS Cardio", defaultSets: 0, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "After workout. HR 110-130. Adjust by feel (Sat=10-15 min).", alternate: "", videoUrl: "https://youtube.com/shorts/JGzA6FPzZS8", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "working" },
];
