import type { InsertExercise } from "@shared/schema";

/**
 * PHASE 3 - CUT BLOCK - 6-Day Specialization Split (v5)
 *
 * Verbatim program content. Every row is keyed by (program, day, order, number);
 * `syncProgram` in ./index.ts upserts on that key so editing a row here updates
 * the DB in place and keeps existing set_logs pointing at the same exercise id.
 */
export const phase3Exercises: Omit<InsertExercise, "program">[] = [

  // ===== DAY 1 — Side Delts + Anterior Delt Press + Triceps (overhead bias) + Rear Delt =====
  // Warm-up
  { day: 1, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. Controlled pace. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Light band. Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -8, number: "W3", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Wide grip. Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -7, number: "W4", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -6, number: "W5", name: "Elephant Walk", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Shoulder + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/GMYMWEkki6U", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -5, number: "W6", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm warm-up before pressing.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -4, number: "R1", name: "High-Incline Sagittal Press — RAMP SET", defaultSets: 1, repRange: "8 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light. Groove the sagittal path.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -3, number: "R2", name: "High-Incline Sagittal Press — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 1, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 1, number: "2", name: "Single-Arm Behind-Body Cable Lateral Raise", defaultSets: 4, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "PRIORITY. Cable starts slightly behind working hip. Upper arm travels 15-30 deg forward of directly sideways. Neutral or mildly pronated hand. Drive the ELBOW away, do not lift with the hand. Controlled reach at the bottom, no torso collapse. End the set when shrugging or rotation materially changes the rep.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 2, number: "3", name: "High-Incline Sagittal-Plane Machine or Smith Press", defaultSets: 3, repRange: "6-10", tempo: "2-1-1-0", rir: "2-3", restSeconds: "150s", notes: "ONLY direct anterior-delt press of the week. Torso 60-75 deg above horizontal. Neutral/semi-supinated handles if available. Elbows travel forward and upward, not fully flared. Wrists stacked over elbows. Lower to deepest pain-free front-delt stretch. Do not rest at lockout.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 3, number: "4", name: "Strict Seated Scapular-Plane DB Lateral Raise", defaultSets: 4, repRange: "10-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "PRIORITY. Seated upright, no leg drive or torso rebound. Raise 15-30 deg forward of directly sideways. Neutral humeral rotation default; mild pronation optional if comfortable. Drive elbows outward, forearms quiet. Raise to shoulder height or slightly above only while the lateral delt is limiting. No forced lat flare, max internal rotation, or shrugging.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 4, number: "5", name: "Cable Overhead Rope Triceps Ext (bent-over)", defaultSets: 4, repRange: "8-12", tempo: "3-0-1-1", rir: "1-2", restSeconds: "90s", notes: "LONG HEAD, max stretch. Day 1 = overhead bias.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 5, number: "6", name: "Seated DB Overhead Triceps Ext (two-hand)", defaultSets: 3, repRange: "10-15", tempo: "3-0-1-1", rir: "1", restSeconds: "75s", notes: "Long head, DB angle. Failure OK last set.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 6, number: "7", name: "Neutral-Grip Reverse Pec Deck", defaultSets: 3, repRange: "15-20", tempo: "2-1-1-0", rir: "1-2", restSeconds: "60-75s", notes: "REAR DELT pattern 1 of 3. Neutral grip where the machine permits. Chest fixed to pad. Arms ~45-70 deg from torso. Drive upper arms outward and backward. Allow controlled scapular movement, avoid exaggerated rhomboid squeeze. Straight set (pec deck pairs only with itself).", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 7, number: "8", name: "Hanging Leg Raise", defaultSets: 2, repRange: "12-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER.", alternate: "", videoUrl: "", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down
  { day: 1, order: 100, number: "C1", name: "Dead Hang", defaultSets: 1, repRange: "2 × 30s", tempo: "—", rir: "—", restSeconds: "15s", notes: "Shoulder decompression.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 101, number: "C2", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative. Not fatiguing.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after pressing + pushdowns.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 2 — Lats (vertical) + Upper Back + Rear Delt + Biceps =====
  // Warm-up
  { day: 2, order: -13, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -12, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -11, number: "W3", name: "Dead Hang", defaultSets: 1, repRange: "2 × 20s", tempo: "—", rir: "—", restSeconds: "10s", notes: "Shoulder decompression + grip activation.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -10, number: "W4", name: "Scapular Pull-Ups", defaultSets: 1, repRange: "8-10", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Depress and retract scapulae. No elbow bend.", alternate: "", videoUrl: "https://youtu.be/d0DVd2V0n7A", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -9, number: "W5", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -8, number: "W6", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM. Prep for overhead pulling.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -7, number: "W7", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep for curls + grip work.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -4, number: "R1", name: "Neutral Pulldown — RAMP SET", defaultSets: 1, repRange: "10 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Groove the lat path. Cue the elbow.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -3, number: "R2", name: "Neutral Pulldown — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 2, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 1, number: "2", name: "Neutral / Semi-Pronated Pulldown (shoulder-width)", defaultSets: 4, repRange: "8-12", tempo: "2-1-1-1", rir: "2-3", restSeconds: "150s", notes: "PRIORITY LAT. Vertical pattern. Full stretch, cue ELBOW not hand.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 2, number: "3", name: "Chest-Supported Low Row (elbow to hip)", defaultSets: 4, repRange: "8-12", tempo: "2-1-1-0", rir: "2", restSeconds: "120s", notes: "PRIORITY LAT. Humerus toward pelvis.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 3, number: "4a", name: "Straight-Arm Cable Pulldown", defaultSets: 3, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "SUPERSET A: cable+cable. PRIORITY lat isolation, stretched.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P3D2-4", segment: "working" },
  { day: 2, order: 4, number: "4b", name: "Single-Arm Cross-Body Cable Rear-Delt Fly", defaultSets: 3, repRange: "15-20", tempo: "2-1-1-0", rir: "1-2", restSeconds: "75s", notes: "SUPERSET A. REAR DELT pattern 2 of 3. Cable across torso to lengthen. Torso turned slightly toward working side. Reach across naturally, then sweep upper arm outward and slightly backward. Do NOT aggressively retract or depress the scapula. End the concentric before it becomes an upper-back row. Optional 3-5 lengthened partials after the final full-ROM set only.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "P3D2-4", segment: "working" },
  { day: 2, order: 5, number: "5", name: "Wide-Grip Seated Cable Row (elbows high, 60-70 deg)", defaultSets: 3, repRange: "10-12", tempo: "2-1-1-0", rir: "2", restSeconds: "120s", notes: "UPPER BACK. Scapular retraction, NOT lat path.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 6, number: "6", name: "Incline DB Curl", defaultSets: 4, repRange: "8-12", tempo: "3-0-1-1", rir: "1-2", restSeconds: "90s", notes: "LONG HEAD, stretched. All lat and back work complete first.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 7, number: "7", name: "Bench-Supported Bayesian Cable Curl", defaultSets: 3, repRange: "10-15", tempo: "3-0-1-1", rir: "1-2", restSeconds: "75-90s", notes: "Incline bench facing AWAY from a low cable. Torso firm against bench. Working upper arm slightly behind torso. Begin near elbow extension without forced lockout. Shoulder angle FIXED, curl through elbow flexion only. Lower into controlled stretch without upper-arm drift. Bench prevents torso drift so logbook progression is trustworthy. Failure OK last set.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 8, number: "8", name: "Ab Wheel Rollout", defaultSets: 3, repRange: "10-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER. Loaded.", alternate: "", videoUrl: "", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down
  { day: 2, order: 100, number: "C1", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 101, number: "C2", name: "Bicep Wall Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Bicep + anterior shoulder.", alternate: "", videoUrl: "https://youtube.com/shorts/j0rdJpN4B8Y", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 102, number: "C3", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Post calf raise work.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after curls + grip work.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 104, number: "C5", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 3 — Primary Chest + Side Delt (machine) + Rear Delt =====
  // Warm-up
  { day: 3, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -8, number: "W3", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -7, number: "W4", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -6, number: "W5", name: "Push-Ups", defaultSets: 1, repRange: "10-15", tempo: "controlled", rir: "—", restSeconds: "—", notes: "Chest + shoulder activation.", alternate: "", videoUrl: "https://youtube.com/shorts/pKZ-lkKKMws", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -5, number: "W6", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep before pressing.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -4, number: "R1", name: "Low-Incline Smith Press — RAMP SET", defaultSets: 1, repRange: "8 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light. Bench 25-35 deg.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 3, order: -3, number: "R2", name: "Low-Incline Smith Press — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 3, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 1, number: "2", name: "Low-Incline Smith Press", defaultSets: 4, repRange: "6-10", tempo: "2-1-1-0", rir: "2-3", restSeconds: "150s", notes: "CHEST 1 of 3. Bench ~25-35 deg. Grip keeps forearms near vertical at the bottom. Descent starts with elbows ~45-70 deg from torso. Modest natural elbow opening near the bottom, no forced extreme flare. Deepest pain-free ROM that preserves shoulder position. Same elbow path on the concentric. NEVER to failure.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 2, number: "3", name: "Split-Handle Converging Machine Press", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-0", rir: "2", restSeconds: "120s", notes: "CHEST 2 of 3. Flat to slight incline, ~0-20 deg. Independent handles that converge naturally. Elbows under or slightly inside wrists. Upper arms may travel slightly behind torso only if pain-free. Press inward and forward, torso against pad. Do NOT use a foam roller or ROM block to manufacture depth.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 3, number: "4", name: "Bench-Supported Low-to-High Cable Fly", defaultSets: 3, repRange: "10-15", tempo: "3-1-1-0", rir: "1-2", restSeconds: "75-90s", notes: "CHEST 3 of 3. Bench ~15-30 deg. Cable origins slightly below shoulder level. Modest, nearly constant elbow bend. Reach into a controlled stretch without anterior humeral glide. Sweep upper arms upward and inward. Stop when further movement requires shoulder elevation or chest collapse. Clavicular-biased adduction, less triceps fatigue than another press.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 4, number: "5", name: "Unilateral Machine Lateral Raise", defaultSets: 5, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "PRIORITY. One arm at a time where the machine permits. Turn slightly so the upper arm moves through the scapular plane. Neutral to mildly internally rotated; do NOT maximally pronate. Drive the elbow outward, stable torso. Allow natural scapular movement, do not forcibly pin or protract. Stop when shrugging materially changes the rep.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 5, number: "6", name: "Prone Incline DB Rear-Delt Raise", defaultSets: 3, repRange: "15-20", tempo: "2-1-1-0", rir: "1-2", restSeconds: "60-75s", notes: "REAR DELT pattern 3 of 3. Chest on an incline bench. Straight set, no superset. Placed after chest and lateral delts.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 6, number: "7", name: "Cable Crunch", defaultSets: 2, repRange: "12-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down
  { day: 3, order: 100, number: "C1", name: "Dead Hang", defaultSets: 1, repRange: "2 × 30s", tempo: "—", rir: "—", restSeconds: "15s", notes: "Shoulder decompression after pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 101, number: "C2", name: "Doorway Pec Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Chest + anterior shoulder.", alternate: "", videoUrl: "https://youtu.be/CEQMx4zFwYs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative. Counterbalance pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 4 — Legs (Braced) =====
  // Warm-up
  { day: 4, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow + quad activation.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Shoulder maintenance even on leg day.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -8, number: "W3", name: "World's Greatest Stretch", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Hip flexors, thoracic, hamstrings — all in one.", alternate: "", videoUrl: "https://youtu.be/-CiWQ2IvY34", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -7, number: "W4", name: "Cossack Squat", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Adductor + hip mobility.", alternate: "", videoUrl: "https://youtube.com/shorts/JfauHQjKVrU", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -6, number: "W5", name: "Pigeon Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip external rotation + glute stretch.", alternate: "", videoUrl: "https://youtube.com/shorts/KUclDkITsS8", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -5, number: "W6", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Prep for calf raises.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -4, number: "R1", name: "Leg Press — RAMP SET", defaultSets: 1, repRange: "10 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "BRACE ON. Light.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -3, number: "R2", name: "Leg Press — RAMP SET", defaultSets: 1, repRange: "6 @ ~70%", tempo: "controlled", rir: "—", restSeconds: "90s", notes: "BRACE ON. Moderate.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 4, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 1, number: "2", name: "Seated Leg Curl", defaultSets: 3, repRange: "10-15", tempo: "2-1-1-1", rir: "2", restSeconds: "90s", notes: "Hams first. Protects low back.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 2, number: "3", name: "Leg Press", defaultSets: 4, repRange: "10-15", tempo: "2-1-1-1", rir: "2-3", restSeconds: "180s", notes: "** BACK BRACE ** Straight sets, never supersetted.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 3, number: "4", name: "Hack Squat", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "2-3", restSeconds: "180s", notes: "** BACK BRACE ** Straight sets, never supersetted.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 4, number: "5a", name: "Lying Leg Curl", defaultSets: 3, repRange: "8-12", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "SUPERSET A: machine+machine, antagonist.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P3D4-5", segment: "working" },
  { day: 4, order: 5, number: "5b", name: "Leg Extension", defaultSets: 3, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "SUPERSET A.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P3D4-5", segment: "working" },
  { day: 4, order: 6, number: "6a", name: "Adductor Machine", defaultSets: 2, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "SUPERSET B. CUT FIRST if recovery slips.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P3D4-6", segment: "working" },
  { day: 4, order: 7, number: "6b", name: "Abductor Machine", defaultSets: 2, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "SUPERSET B. CUT FIRST if recovery slips.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "P3D4-6", segment: "working" },
  { day: 4, order: 8, number: "7", name: "Standing Calf Raise", defaultSets: 4, repRange: "10-15", tempo: "2-1-1-1", rir: "1-2", restSeconds: "60s", notes: "Standing. Gastroc.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 9, number: "8", name: "Weighted Decline Sit-up", defaultSets: 3, repRange: "12-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER.", alternate: "Cable Crunch", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down (Day 4 uses M-prefix)
  { day: 4, order: 100, number: "M1", name: "Pigeon Pose", defaultSets: 1, repRange: "45s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Deep hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/KUclDkITsS8", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 101, number: "M2", name: "Couch Stretch", defaultSets: 1, repRange: "45s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip flexor restoration.", alternate: "", videoUrl: "https://youtu.be/ulgAOykAgV4", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 102, number: "M3", name: "Elephant Walk", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Shoulder + hip combined mobility.", alternate: "", videoUrl: "https://youtube.com/shorts/GMYMWEkki6U", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 103, number: "M4", name: "Frog Stretch", defaultSets: 1, repRange: "60s", tempo: "—", rir: "—", restSeconds: "—", notes: "Adductor + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 104, number: "M5", name: "Dead Hang", defaultSets: 1, repRange: "60s", tempo: "—", rir: "—", restSeconds: "—", notes: "Extended hold — full decompression.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 105, number: "M6", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Daily shoulder maintenance.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 5 — Lateral Delts + Triceps (pushdown / lockout bias) =====
  // Warm-up
  { day: 5, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. Controlled pace. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Light band. Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -8, number: "W3", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Wide grip. Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -7, number: "W4", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -6, number: "W5", name: "Elephant Walk", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Shoulder + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/GMYMWEkki6U", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -5, number: "W6", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm warm-up before pressing.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -4, number: "R1", name: "Lateral Raise — RAMP SET", defaultSets: 1, repRange: "15 @ light", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Groove the path. No press today.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 5, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 1, number: "2", name: "Single-Arm Cable Lateral Raise (knee-height pulley)", defaultSets: 4, repRange: "12-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "PRIORITY. Knee-height pulley = different resistance curve than Day 1 behind-body. Drive the elbow, stable torso.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Replaced the lean-away cable lateral raise. Bilateral, not per-side — the
  // sheet's Unilateral column says N, and an upright row is a two-hand bar.
  { day: 5, order: 2, number: "3", name: "Wide-Grip Cable Upright Row", defaultSets: 3, repRange: "12-20", tempo: "2-0-1-1", rir: "1", restSeconds: "75s", notes: "PRIORITY side delt. WIDE grip (outside shoulder width). Stop when elbows reach shoulder height, no higher. Lead with the elbows, out and up. Higher pull or narrow grip shifts load to traps - keep traps moderate for the shoulder line. Failure OK last set.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 3, number: "4", name: "Bench-Supported Cable Triceps Pushdown", defaultSets: 4, repRange: "10-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "LATERAL/MEDIAL head, lockout. Day 5 = pushdown bias. Bench support removes torso drift so progression is trustworthy.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 4, number: "5", name: "Machine Triceps Extension", defaultSets: 3, repRange: "10-15", tempo: "2-0-1-1", rir: "1", restSeconds: "75s", notes: "Full lockout, medial head. Failure OK last set.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 5, number: "6", name: "Cable Face Pull", defaultSets: 2, repRange: "15-25", tempo: "2-1-1-1", rir: "2", restSeconds: "60s", notes: "JOINT HEALTH. Not counted as hypertrophy volume.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 6, number: "7", name: "Hanging Leg Raise (weighted)", defaultSets: 2, repRange: "15-20", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down
  { day: 5, order: 100, number: "C1", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 101, number: "C2", name: "Bicep Wall Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Bicep + anterior shoulder.", alternate: "", videoUrl: "https://youtube.com/shorts/j0rdJpN4B8Y", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after curls + tricep work.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 104, number: "C5", name: "Neck Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Trap + neck tension release.", alternate: "", videoUrl: "https://youtube.com/shorts/YD3obQOMhrs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 6 — Lats (bench-supported pulldown, pull-in, pullover) + Upper Back + Chest + Biceps =====
  // Warm-up
  { day: 6, order: -13, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -12, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -11, number: "W3", name: "Dead Hang", defaultSets: 1, repRange: "2 × 20s", tempo: "—", rir: "—", restSeconds: "10s", notes: "Shoulder decompression + grip activation.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -10, number: "W4", name: "Scapular Pull-Ups", defaultSets: 1, repRange: "8-10", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Scapular depression + retraction.", alternate: "", videoUrl: "https://youtu.be/d0DVd2V0n7A", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -9, number: "W5", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -8, number: "W6", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -7, number: "W7", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep for curls + tricep work.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -4, number: "R1", name: "Bench-Supported Single-Arm High-Cable Pulldown — RAMP SET", defaultSets: 1, repRange: "12 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Groove the high-to-low path with bench support.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -3, number: "R2", name: "Bench-Supported Single-Arm High-Cable Pulldown — RAMP SET", defaultSets: 1, repRange: "8 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  // Working Sets
  { day: 6, order: 0, number: "1", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "EVERY DAY, FIRST. Posing practice. NOT counted as volume.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 1, number: "2", name: "Bench-Supported Single-Arm High-Cable Pulldown", defaultSets: 3, repRange: "10-15", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "PRIORITY LAT 1 of 3. Bench support removes torso drift and rotation. High-to-low path, max ROM for long arms. FIRST among Day 6 lat movements.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 2, number: "3", name: "Unilateral Cable Lat Pull-In (toward hip)", defaultSets: 4, repRange: "10-15", tempo: "2-1-1-1", rir: "2", restSeconds: "120s", notes: "PRIORITY LAT 2 of 3. Distinct adduction/pull-in path after the high-to-low pulldown. Torso stable, resist rotation. Do NOT shorten the lengthened position to increase load.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 3, number: "4", name: "Machine / Cable Pullover", defaultSets: 3, repRange: "10-15", tempo: "2-1-1-1", rir: "1-2", restSeconds: "90s", notes: "PRIORITY LAT 3 of 3. Stable torso, controlled shoulder-flexion stretch. Drive the upper arms down without turning it into elbow extension. Stop before lumbar extension or rib flare replaces shoulder movement.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 4, number: "5", name: "Chest-Supported Upper-Back Row (elbows 45-70 deg)", defaultSets: 4, repRange: "8-12", tempo: "2-1-1-0", rir: "2", restSeconds: "120s", notes: "UPPER BACK. Chest fixed to pad. Drive elbows OUTWARD, not toward the hips. Controlled scapular retraction without lumbar extension. Prevents a lat-only back program.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 5, number: "6", name: "Low-Incline DB Press", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-0", rir: "2", restSeconds: "120s", notes: "CHEST 1 of 2. Bench ~15-30 deg. Neutral or semi-pronated grip per shoulder comfort. Lower beside the upper chest with natural elbow opening. Deepest controlled ROM preserving shoulder position. Press up and slightly inward, no banging. NO curl superset.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 6, number: "7", name: "Bench-Supported Mid-Height Cable Fly", defaultSets: 3, repRange: "10-15", tempo: "3-1-1-0", rir: "1-2", restSeconds: "75-90s", notes: "CHEST 2 of 2. Receives the 3 fly sets relocated from Day 3. Flat bench or incline <=15 deg. Cable origins ~mid-chest height. Slight, nearly constant elbow bend. Upper arms travel behind torso only as far as the shoulder tolerates. Sweep inward without shrugging or rolling shoulders forward.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 7, number: "8", name: "Hammer Curl", defaultSets: 3, repRange: "10-12", tempo: "2-0-1-1", rir: "1-2", restSeconds: "75s", notes: "BRACHIALIS. Straight set, no superset.", alternate: "", videoUrl: "", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 8, number: "9", name: "Preacher Curl (EZ or machine)", defaultSets: 3, repRange: "10-12", tempo: "2-0-1-1", rir: "1", restSeconds: "75s", notes: "SHORT HEAD, shortened position. Failure OK last set.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 9, number: "10", name: "Weighted Cable Crunch", defaultSets: 2, repRange: "12-15", tempo: "2-0-1-1", rir: "1-2", restSeconds: "60s", notes: "AB FINISHER.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  // Cool-down
  { day: 6, order: 100, number: "C1", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 101, number: "C2", name: "Bicep Wall Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Bicep + anterior shoulder.", alternate: "", videoUrl: "https://youtube.com/shorts/j0rdJpN4B8Y", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after curls + tricep work.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 104, number: "C5", name: "Neck Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Trap + neck tension release.", alternate: "", videoUrl: "https://youtube.com/shorts/YD3obQOMhrs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
];
