import type { InsertExercise } from "@shared/schema";

/**
 * PHASE 1 - BASE BLOCK - 6-day split (warm-ups, working sets, finishers, cool-downs)
 *
 * Verbatim program content. Every row is keyed by (program, day, order, number);
 * `syncProgram` in ./index.ts upserts on that key so editing a row here updates
 * the DB in place and keeps existing set_logs pointing at the same exercise id.
 */
export const phase1Exercises: Omit<InsertExercise, "program">[] = [

  // ===== DAY 1 — Monday: Delt Dominant + Triceps + Core =====
  
  // Day 1 Warm-Up
  { day: 1, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. Controlled pace. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Light band. Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -8, number: "W3", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Wide grip. Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -7, number: "W4", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -6, number: "W5", name: "Elephant Walk", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Shoulder + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/GMYMWEkki6U", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -5, number: "W6", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm warm-up before pressing.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -4, number: "R1", name: "Seated DB Shoulder Press — RAMP SET", defaultSets: 1, repRange: "8 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light. Groove the pattern.", alternate: "", videoUrl: "https://youtube.com/shorts/7oH0algsdww", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 1, order: -3, number: "R2", name: "Seated DB Shoulder Press — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate. Prep the joints.", alternate: "", videoUrl: "https://youtube.com/shorts/7oH0algsdww", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  
  // Day 1 Working Sets
  { day: 1, order: 1, number: "1", name: "Neutral Grip Seated DB Shoulder Press", defaultSets: 3, repRange: "6-10", tempo: "2-1-1-1", rir: "2", restSeconds: "120s", notes: "Stop 1-2 reps before form slows", alternate: "", videoUrl: "https://youtube.com/shorts/7oH0algsdww", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 2, number: "2", name: "Lean-In DB Lateral Raise", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60-75s", notes: "Slight pause at top, control down", alternate: "Cable", videoUrl: "https://youtube.com/shorts/HeovYNoZDRg", inputType: "weight_reps_unilateral_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 1, order: 3, number: "3a", name: "Behind the Back Single-Arm Band Lateral Raise", defaultSets: 3, repRange: "15-25", tempo: "2-0-2-1", rir: "0-1", restSeconds: "45-60s", notes: "Constant tension finish work", alternate: "Band", videoUrl: "https://youtu.be/ihG4lDlTJ-g", inputType: "reps_unilateral_band", isSupersetPart: true, supersetGroup: "D1-3", segment: "working" },
  { day: 1, order: 4, number: "3b", name: "Tricep Rope Pushdown", defaultSets: 3, repRange: "10-15", tempo: "2-0-1-1", rir: "1", restSeconds: "60-75s", notes: "Lock in elbows; full extension", alternate: "Band", videoUrl: "https://youtube.com/shorts/u36jNfqh8_U", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D1-3", segment: "working" },
  { day: 1, order: 5, number: "4a", name: "Prone Incline Rear Delt Fly", defaultSets: 3, repRange: "12-20", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Keep scapula stable; no swinging", alternate: "", videoUrl: "https://youtube.com/shorts/vzQmQN3hpYY", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D1-4", segment: "working" },
  { day: 1, order: 6, number: "4b", name: "Overhead Cable Tricep Extension", defaultSets: 3, repRange: "10-14", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75-90s", notes: "Choose elbow-friendly option", alternate: "DB OH Ext", videoUrl: "https://youtube.com/shorts/9Ark9S11uXw", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D1-4", segment: "working" },
  { day: 1, order: 7, number: "5a", name: "Lying Bench Leg Lifts", defaultSets: 3, repRange: "10-15", tempo: "—", rir: "", restSeconds: "30s", notes: "Lower ab focus. Add ankle weights if possible", alternate: "Bench", videoUrl: "https://youtube.com/shorts/KCt2qWYPrMc", inputType: "bodyweight_reps_weighted", isSupersetPart: true, supersetGroup: "D1-5", segment: "working" },
  { day: 1, order: 8, number: "5b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Quality > duration", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "D1-5", segment: "working" },
  
  // Day 1 Cool-Down
  { day: 1, order: 100, number: "C1", name: "Dead Hang", defaultSets: 1, repRange: "2 × 30s", tempo: "—", rir: "—", restSeconds: "15s", notes: "Shoulder decompression.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 101, number: "C2", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative. Not fatiguing.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 1, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after pressing + pushdowns.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 2 — Tuesday: Lat Width + Biceps =====
  
  // Day 2 Warm-Up
  { day: 2, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -8, number: "W3", name: "Dead Hang", defaultSets: 1, repRange: "2 × 20s", tempo: "—", rir: "—", restSeconds: "10s", notes: "Shoulder decompression + grip activation.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -7, number: "W4", name: "Scapular Pull-Ups", defaultSets: 1, repRange: "8-10", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Depress and retract scapulae. No elbow bend.", alternate: "", videoUrl: "https://youtu.be/d0DVd2V0n7A", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -6, number: "W5", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -5, number: "W6", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM. Prep for overhead pulling.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -4, number: "W7", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep for curls + grip work.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -3, number: "R1", name: "Neutral Grip Pull-Up — RAMP SET", defaultSets: 1, repRange: "3 @ assisted/light", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light assistance or slow negatives. Groove the pattern.", alternate: "", videoUrl: "https://youtube.com/shorts/E9vvwfxSZFc", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 2, order: -2, number: "R2", name: "Neutral Grip Pull-Up — RAMP SET", defaultSets: 1, repRange: "3 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate. Prep the joints. Full hang to full pull.", alternate: "", videoUrl: "https://youtube.com/shorts/E9vvwfxSZFc", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  
  // Day 2 Working Sets
  { day: 2, order: 1, number: "1", name: "Neutral Grip Strict Pull-Up", defaultSets: 3, repRange: "6-10", tempo: "2-1-1-1", rir: "2", restSeconds: "120s", notes: "Width anchor", alternate: "", videoUrl: "https://youtube.com/shorts/E9vvwfxSZFc", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 2, number: "2", name: "1-Arm Half-Kneeling Cable Lat Pulldown", defaultSets: 3, repRange: "8-12/side", tempo: "2-1-1-1", rir: "1-2", restSeconds: "60-90s", notes: "Pull elbow into back pocket", alternate: "", videoUrl: "https://youtube.com/shorts/wYy32uk4Bu8", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 2, order: 3, number: "3a", name: "Straight-Arm Pulldown", defaultSets: 3, repRange: "12-20", tempo: "2-1-1-1", rir: "1-2", restSeconds: "60s", notes: "Ribcage down; no lumbar extension", alternate: "", videoUrl: "https://youtube.com/shorts/hAMcfubonDc", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D2-3", segment: "working" },
  { day: 2, order: 4, number: "3b", name: "Hammer Curl", defaultSets: 3, repRange: "10", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75s", notes: "Neutral grip. Full ROM.", alternate: "", videoUrl: "https://youtube.com/shorts/ZFV_yAlxLMU", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D2-3", segment: "working" },
  { day: 2, order: 5, number: "4a", name: "Chest-Supported DB Row (lat-biased, elbow ~30°)", defaultSets: 3, repRange: "8-12", tempo: "2-1-1-1", rir: "2", restSeconds: "90-120s", notes: "Don't flare elbows (save for thickness day)", alternate: "", videoUrl: "https://youtube.com/shorts/eVm92NO-EYI", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D2-4", segment: "working" },
  { day: 2, order: 6, number: "4b", name: "Cable Curl", defaultSets: 3, repRange: "10", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75s", notes: "Neutral or supinated grip. Full stretch at bottom.", alternate: "", videoUrl: "https://youtube.com/shorts/6n3uYGhIoZI", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D2-4", segment: "working" },
  { day: 2, order: 7, number: "5a", name: "DB Standing Calf Raise", defaultSets: 3, repRange: "8-12", tempo: "2-1-2-1", rir: "1-2", restSeconds: "60-75s", notes: "1-sec stretch + 1-sec squeeze", alternate: "BB in Rack", videoUrl: "https://youtube.com/shorts/baEXLy09Ncc", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D2-5", segment: "working" },
  { day: 2, order: 8, number: "5b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Optional here", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "D2-5", segment: "working" },
  { day: 2, order: 9, number: "6", name: "Nordic Curl", defaultSets: 3, repRange: "4-6", tempo: "3-1-1-0", rir: "1-2", restSeconds: "90s", notes: "Use partner or anchor. Control the eccentric. Catch at bottom if needed.", alternate: "", videoUrl: "https://youtube.com/shorts/sRJNSuOzOLU", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  
  // Day 2 Finisher
  { day: 2, order: 10, number: "F1", name: "Reverse Sled Drag", defaultSets: 1, repRange: "100-160 yds", tempo: "AFAP", rir: "—", restSeconds: "—", notes: "As fast as possible. Max effort sprint.", alternate: "", videoUrl: "https://youtu.be/k7JsvdG9sSo", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "finisher" },
  
  // Day 2 Cool-Down
  { day: 2, order: 100, number: "C1", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 101, number: "C2", name: "Bicep Wall Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Bicep + anterior shoulder.", alternate: "", videoUrl: "https://youtube.com/shorts/j0rdJpN4B8Y", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 102, number: "C3", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Post calf raise work.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after curls + grip work.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 2, order: 104, number: "C5", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 3 — Wednesday: Posing + LISS =====
  
  // Day 3 has no warm-up (LISS is the warm-up)
  
  // Day 3 Working Sets
  { day: 3, order: 1, number: "—", name: "Men's Physique Posing Practice", defaultSets: 0, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "Front, Side L, Back, Side R — 60s holds, 3-4 cycles", alternate: "", videoUrl: "https://youtu.be/knbFPNtI_Gc", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 2, number: "—", name: "LISS Cardio", defaultSets: 0, repRange: "20-30 min", tempo: "—", rir: "—", restSeconds: "—", notes: "HR 110-130 range", alternate: "", videoUrl: "https://youtube.com/shorts/JGzA6FPzZS8", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 3, order: 3, number: "—", name: "Stomach Vacuum", defaultSets: 3, repRange: "45-60s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  
  // Day 3 Cool-Down (Post-Session Mobility)
  { day: 3, order: 100, number: "M1", name: "Pigeon Pose", defaultSets: 1, repRange: "45s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Deep hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/KUclDkITsS8", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 101, number: "M2", name: "Couch Stretch", defaultSets: 1, repRange: "45s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip flexor restoration.", alternate: "", videoUrl: "https://youtu.be/ulgAOykAgV4", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 102, number: "M3", name: "Elephant Walk", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Shoulder + hip combined mobility.", alternate: "", videoUrl: "https://youtube.com/shorts/GMYMWEkki6U", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 103, number: "M4", name: "Frog Stretch", defaultSets: 1, repRange: "60s", tempo: "—", rir: "—", restSeconds: "—", notes: "Adductor + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 104, number: "M5", name: "Dead Hang", defaultSets: 1, repRange: "60s", tempo: "—", rir: "—", restSeconds: "—", notes: "Extended hold — full decompression.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 3, order: 105, number: "M6", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Daily shoulder maintenance.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 4 — Thursday: Upper Chest + Core =====
  
  // Day 4 Warm-Up
  { day: 4, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -8, number: "W3", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -7, number: "W4", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -6, number: "W5", name: "Push-Ups", defaultSets: 1, repRange: "10-15", tempo: "controlled", rir: "—", restSeconds: "—", notes: "Chest + shoulder activation.", alternate: "", videoUrl: "https://youtube.com/shorts/pKZ-lkKKMws", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 4, order: -5, number: "W6", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep before pressing.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  
  // Day 4 Working Sets
  { day: 4, order: 1, number: "1", name: "Incline DB Bench Press", defaultSets: 4, repRange: "6-10", tempo: "2-1-1-0", rir: "1-2", restSeconds: "120s", notes: "Slight arch OK; keep shoulder packed", alternate: "", videoUrl: "https://youtube.com/shorts/ou6s32mJgjU", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 2, number: "2", name: "BB Bench Press", defaultSets: 4, repRange: "8-10", tempo: "2-1-1-0", rir: "1-2", restSeconds: "120s", notes: "Suggested start: 135-185 lbs. Last set to failure. Full ROM, controlled descent.", alternate: "", videoUrl: "https://youtube.com/shorts/oJP4g7bJH5Y", inputType: "weight_reps_barbell", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 3, number: "3a", name: "Incline DB Fly", defaultSets: 3, repRange: "12-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Control the arc. Slight bend in elbow. Stretch at bottom.", alternate: "", videoUrl: "https://youtube.com/shorts/VSwFnBqe7gE", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D4-3", segment: "working" },
  { day: 4, order: 4, number: "3b", name: "Banded Face Pull", defaultSets: 3, repRange: "15-25", tempo: "2-1-2-1", rir: "1-2", restSeconds: "60s", notes: "Scapular hygiene", alternate: "", videoUrl: "https://youtube.com/shorts/8686PLZB_1Q", inputType: "band_reps", isSupersetPart: true, supersetGroup: "D4-3", segment: "working" },
  { day: 4, order: 5, number: "4a", name: "DB Pullover", defaultSets: 3, repRange: "12-15", tempo: "3-1-2-0", rir: "1-2", restSeconds: "60s", notes: "Lat stretch + upper chest. Keep elbows soft.", alternate: "", videoUrl: "https://youtube.com/shorts/dXFMzZUALNM", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D4-4", segment: "working" },
  { day: 4, order: 6, number: "4b", name: "Seated DB Side Lateral Raise", defaultSets: 3, repRange: "12-20", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Controlled reps, no bounce", alternate: "", videoUrl: "https://youtube.com/shorts/JIhbYYA1Q90", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D4-4", segment: "working" },
  { day: 4, order: 7, number: "5a", name: "Walking Lunges", defaultSets: 3, repRange: "12/leg", tempo: "3-1-1-0", rir: "1-2", restSeconds: "75s", notes: "Controlled steps. Full ROM each leg.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "D4-5", segment: "working" },
  { day: 4, order: 8, number: "5b", name: "Ab Wheel Rollout", defaultSets: 3, repRange: "10-15", tempo: "3-1-2-0", rir: "1-2", restSeconds: "60s", notes: "Kneeling. Full extension, no lumbar hyperextension. Slow eccentric.", alternate: "Barbell Rollout", videoUrl: "", inputType: "bodyweight_reps_weighted", isSupersetPart: true, supersetGroup: "D4-5", segment: "working" },
  { day: 4, order: 9, number: "6", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s hold", tempo: "—", rir: "skill", restSeconds: "30s", notes: "Daily practice pays off.", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 4, order: 10, number: "7", name: "Cable Woodchop", defaultSets: 3, repRange: "12-15/side", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Core rotation. 20-30 lbs. High to low.", alternate: "", videoUrl: "https://youtube.com/shorts/I4bKRKNk2JE", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  
  // Day 4 Cool-Down
  { day: 4, order: 100, number: "C1", name: "Dead Hang", defaultSets: 1, repRange: "2 × 30s", tempo: "—", rir: "—", restSeconds: "15s", notes: "Shoulder decompression after pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 101, number: "C2", name: "Doorway Pec Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Chest + anterior shoulder.", alternate: "", videoUrl: "https://youtu.be/CEQMx4zFwYs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative. Counterbalance pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 4, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after pressing.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 5 — Friday: Back Thickness + Rear Delts + Arms =====
  
  // Day 5 Warm-Up
  { day: 5, order: -10, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -9, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rotator cuff activation.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -8, number: "W3", name: "Dead Hang", defaultSets: 1, repRange: "2 × 20s", tempo: "—", rir: "—", restSeconds: "10s", notes: "Shoulder decompression + grip activation.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -7, number: "W4", name: "Scapular Pull-Ups", defaultSets: 1, repRange: "8-10", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Scapular depression + retraction.", alternate: "", videoUrl: "https://youtu.be/d0DVd2V0n7A", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -6, number: "W5", name: "Band Pull-Aparts", defaultSets: 1, repRange: "15-20", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Rear delt + scapular activation.", alternate: "", videoUrl: "https://youtube.com/shorts/SuvO4TBwSu4", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -5, number: "W6", name: "Shoulder Dislocates (Band)", defaultSets: 1, repRange: "10-12", tempo: "slow", rir: "—", restSeconds: "—", notes: "Full ROM.", alternate: "", videoUrl: "https://youtu.be/a9rqTzZaI7s", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 5, order: -4, number: "W7", name: "Wrist Circles", defaultSets: 1, repRange: "10 each direction", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm prep for curls + tricep work.", alternate: "", videoUrl: "", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  
  // Day 5 Working Sets
  { day: 5, order: 1, number: "1", name: "Strict Narrow Grip Chin-Up", defaultSets: 4, repRange: "6-10", tempo: "2-1-1-1", rir: "1-2", restSeconds: "120-150s", notes: "", alternate: "", videoUrl: "https://youtu.be/88bye9FlQR8", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 2, number: "2a", name: "1-Arm DB Row (strict, bench supported)", defaultSets: 3, repRange: "8-12/side", tempo: "2-1-1-1", rir: "1-2", restSeconds: "75-90s", notes: "Pull to hip for lats, higher for mid-back", alternate: "", videoUrl: "https://youtube.com/shorts/Ppl6i4-o5kk", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "D5-2", segment: "working" },
  { day: 5, order: 3, number: "2b", name: "Chest-Supported DB Shrug", defaultSets: 3, repRange: "10-15", tempo: "2-1-2-1", rir: "1-2", restSeconds: "75-90s", notes: "Traps help frame if not overdone", alternate: "", videoUrl: "https://youtube.com/shorts/QszCnEqqklU", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D5-2", segment: "working" },
  { day: 5, order: 4, number: "3a", name: "DB Pullover", defaultSets: 3, repRange: "12-15", tempo: "3-1-2-0", rir: "1-2", restSeconds: "60s", notes: "Full lat stretch at bottom. Keep elbows soft.", alternate: "", videoUrl: "https://youtube.com/shorts/dXFMzZUALNM", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D5-3", segment: "working" },
  { day: 5, order: 5, number: "3b", name: "Banded Straight-Arm Cross-Body Delt Fly", defaultSets: 3, repRange: "12-20/side", tempo: "2-0-2-1", rir: "0-1", restSeconds: "45-60s", notes: "Keep shoulders out of ears", alternate: "", videoUrl: "https://youtube.com/shorts/P5CXx_jgTDE", inputType: "reps_unilateral_band", isSupersetPart: true, supersetGroup: "D5-3", segment: "working" },
  { day: 5, order: 6, number: "3d", name: "DB Lateral Raise", defaultSets: 3, repRange: "12-15", tempo: "2-0-2-1", rir: "1-2", restSeconds: "60s", notes: "Suggested start: 15-20 lbs. Controlled arc. No shrugging.", alternate: "", videoUrl: "https://youtube.com/shorts/JIhbYYA1Q90", inputType: "weight_reps_db", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 5, order: 7, number: "3c", name: "Spider Curl", defaultSets: 3, repRange: "12", tempo: "2-0-2-1", rir: "1-2", restSeconds: "75-90s", notes: "Chest on incline bench. Full hang, full squeeze.", alternate: "", videoUrl: "https://youtube.com/shorts/HT2Z1MbRXVE", inputType: "weight_reps_db", isSupersetPart: true, supersetGroup: "D5-3", segment: "working" },
  { day: 5, order: 8, number: "4a", name: "DB Tricep Kickback", defaultSets: 3, repRange: "10-15", tempo: "2-0-2-1", rir: "1", restSeconds: "75-90s", notes: "Full lockout, squeeze at peak contraction. Keep upper arm fixed.", alternate: "Cable Kickback", videoUrl: "", inputType: "weight_reps_unilateral_db", isSupersetPart: true, supersetGroup: "D5-4", segment: "working" },
  { day: 5, order: 9, number: "4b", name: "Stomach Vacuum", defaultSets: 3, repRange: "30-45s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: true, supersetGroup: "D5-4", segment: "working" },
  
  // Day 5 Cool-Down
  { day: 5, order: 100, number: "C1", name: "Cross-Body Child's Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Lat + shoulder stretch.", alternate: "", videoUrl: "https://youtu.be/FPHDSZJw3EY", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 101, number: "C2", name: "Bicep Wall Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Bicep + anterior shoulder.", alternate: "", videoUrl: "https://youtube.com/shorts/j0rdJpN4B8Y", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 102, number: "C3", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Restorative.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 103, number: "C4", name: "Wrist Flexor/Extensor Stretch", defaultSets: 1, repRange: "30s each", tempo: "—", rir: "—", restSeconds: "—", notes: "Forearm recovery after curls + tricep work.", alternate: "", videoUrl: "https://youtube.com/shorts/63LEj3oP6lA", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 5, order: 104, number: "C5", name: "Neck Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Trap + neck tension release.", alternate: "", videoUrl: "https://youtube.com/shorts/YD3obQOMhrs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },

  // ===== DAY 6 — Saturday: Legs (Maintenance) + Core =====
  
  // Day 6 Warm-Up
  { day: 6, order: -12, number: "W1", name: "Slow Sled Drag (Forward)", defaultSets: 1, repRange: "2 × 20 yds", tempo: "slow", rir: "—", restSeconds: "—", notes: "Light load. General blood flow + quad activation.", alternate: "", videoUrl: "https://youtu.be/9XRRXaUpnLk", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -11, number: "W2", name: "Band External Rotation", defaultSets: 1, repRange: "15-20/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Shoulder maintenance even on leg day.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -10, number: "W3", name: "World's Greatest Stretch", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Hip flexors, thoracic, hamstrings — all in one.", alternate: "", videoUrl: "https://youtu.be/-CiWQ2IvY34", inputType: "cardio", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -9, number: "W4", name: "Cossack Squat", defaultSets: 1, repRange: "5/side", tempo: "slow", rir: "—", restSeconds: "—", notes: "Adductor + hip mobility.", alternate: "", videoUrl: "https://youtube.com/shorts/JfauHQjKVrU", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -8, number: "W5", name: "Pigeon Pose", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip external rotation + glute stretch.", alternate: "", videoUrl: "https://youtube.com/shorts/KUclDkITsS8", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -7, number: "W6", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Prep for calf raises.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -4, number: "R1", name: "Belt Squat — RAMP SET", defaultSets: 1, repRange: "8 @ ~50%", tempo: "controlled", rir: "—", restSeconds: "30s", notes: "Light. Groove the pattern.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  { day: 6, order: -3, number: "R2", name: "Belt Squat — RAMP SET", defaultSets: 1, repRange: "6 @ ~65%", tempo: "controlled", rir: "—", restSeconds: "60s", notes: "Moderate. Prep the joints.", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "warmup" },
  
  // Day 6 Working Sets
  { day: 6, order: 1, number: "1", name: "Belt Squat", defaultSets: 4, repRange: "6-10", tempo: "3-1-1-0", rir: "2", restSeconds: "120-150s", notes: "Quad anchor with low spinal load", alternate: "", videoUrl: "", inputType: "weight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 2, number: "2a", name: "B-Stance DB RDL", defaultSets: 3, repRange: "8-12/leg", tempo: "3-1-1-0", rir: "1-2", restSeconds: "75-90s", notes: "Stretch hamstrings; don't chase load", alternate: "", videoUrl: "https://youtube.com/shorts/GUsVaTXNmpM", inputType: "weight_reps_unilateral", isSupersetPart: true, supersetGroup: "D6-2", segment: "working" },
  { day: 6, order: 3, number: "2b", name: "BB Hip Thrust", defaultSets: 3, repRange: "8-12", tempo: "2-1-2-1", rir: "1-2", restSeconds: "120s", notes: "Stop when you can't control descent", alternate: "", videoUrl: "https://youtube.com/shorts/Bh3DVRq_arE", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D6-2", segment: "working" },
  { day: 6, order: 4, number: "3a", name: "Reverse Hyper", defaultSets: 3, repRange: "10-15", tempo: "2-1-2-1", rir: "1-2", restSeconds: "75-90s", notes: "Glute/ham without frying you", alternate: "", videoUrl: "https://youtube.com/shorts/5Z2iTnhb5qM", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D6-3", segment: "working" },
  { day: 6, order: 5, number: "3b", name: "Belt Squat Calf Raise", defaultSets: 3, repRange: "8-12", tempo: "2-1-2-1", rir: "1-2", restSeconds: "60-75s", notes: "1-sec stretch + 1-sec squeeze", alternate: "BB in Rack", videoUrl: "https://youtu.be/DjND7ICwWxI", inputType: "weight_reps", isSupersetPart: true, supersetGroup: "D6-3", segment: "working" },
  { day: 6, order: 6, number: "4a", name: "RKC Plank", defaultSets: 3, repRange: "20-40s", tempo: "—", rir: "5s rsv", restSeconds: "60s", notes: "Anti-extension; waist-friendly", alternate: "", videoUrl: "https://youtu.be/DGJccwYZWFA", inputType: "timed", isSupersetPart: true, supersetGroup: "D6-4", segment: "working" },
  { day: 6, order: 7, number: "4b", name: "Deadbug", defaultSets: 3, repRange: "10/side", tempo: "3-1-1-0", rir: "2", restSeconds: "60s", notes: "Only if low back feels perfect", alternate: "", videoUrl: "https://youtube.com/shorts/DqLL45uk2Tk", inputType: "timed_reps", isSupersetPart: true, supersetGroup: "D6-4", segment: "working" },
  { day: 6, order: 8, number: "5", name: "Stomach Vacuum", defaultSets: 3, repRange: "45-60s", tempo: "—", rir: "skill", restSeconds: "30s", notes: "", alternate: "", videoUrl: "https://youtube.com/shorts/rmllHP_DHvQ", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 9, number: "6", name: "Walking Lunges", defaultSets: 3, repRange: "10/leg", tempo: "2-1-1-0", rir: "1-2", restSeconds: "90s", notes: "Controlled steps. Full ROM each leg.", alternate: "", videoUrl: "", inputType: "weight_reps_unilateral", isSupersetPart: false, supersetGroup: null, segment: "working" },
  { day: 6, order: 10, number: "7", name: "Glute Ham Sliders", defaultSets: 3, repRange: "10", tempo: "3-0-1-1", rir: "1-2", restSeconds: "60-75s", notes: "Slow eccentric. Control the slide out.", alternate: "", videoUrl: "", inputType: "bodyweight_reps", isSupersetPart: false, supersetGroup: null, segment: "working" },
  
  // Day 6 Cool-Down
  { day: 6, order: 100, number: "C1", name: "Couch Stretch", defaultSets: 1, repRange: "45s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Hip flexor + quad stretch. Deep hold.", alternate: "", videoUrl: "https://youtu.be/ulgAOykAgV4", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 101, number: "C2", name: "Frog Stretch", defaultSets: 1, repRange: "60s", tempo: "—", rir: "—", restSeconds: "—", notes: "Adductor + hip opener.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 102, number: "C3", name: "Dead Hang", defaultSets: 1, repRange: "2 × 30s", tempo: "—", rir: "—", restSeconds: "15s", notes: "Spinal decompression after squatting.", alternate: "", videoUrl: "https://youtube.com/shorts/dOCQjaasbGs", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 103, number: "C4", name: "Calf Stretch", defaultSets: 1, repRange: "30s/side", tempo: "—", rir: "—", restSeconds: "—", notes: "Post calf raise recovery.", alternate: "", videoUrl: "https://youtube.com/shorts/-SJ1pnldEGU", inputType: "timed", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
  { day: 6, order: 104, number: "C5", name: "Band External Rotation (Light)", defaultSets: 1, repRange: "10-12/side", tempo: "2-1-2-0", rir: "—", restSeconds: "—", notes: "Daily shoulder maintenance.", alternate: "", videoUrl: "https://youtube.com/shorts/7DqYesMRkzU", inputType: "band_reps", isSupersetPart: false, supersetGroup: null, segment: "cooldown" },
];
